### ISSUE TITLE
Impossible to configure module

### ISSUE THREAD

**Issue by youness** [owebia/magento2-module-advanced-shipping-setting#1]
I'm getting this error when i try to configure owebia shipping method:
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Owebia\AdvancedShippingSetting\Block\System\Config\Form\Field\Config::translate

maybe, you must implement 'translate' protected method or use __('...') instead

**Comment by owebia** [comment]
Hi,
Are you using the last version of the project ?
This has been fixed here:
https://github.com/owebia/magento2-module-advanced-shipping-setting/commit/4b9c8f6ae5c6f6cf08087d92e62cc76cf3a6e67c

**Comment by youness** [comment]
Hi,
Think you for your response. I used composer to install and update module. However, i got 2.0.1 version !!!

composer require owebia/magento2-module-advanced-shipping-setting:^2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing nikic/php-parser (v2.0.1)
    Loading from cache

  - Installing owebia/magento2-module-advanced-setting-core (2.0.1)
    Downloading: 100%

  - Installing owebia/magento2-module-advanced-shipping-setting (2.0)
    Downloading: 100%

**Comment by owebia** [comment]
And if you try
```
composer require owebia/magento2-module-advanced-shipping-setting:^2.0.2
```
Does it work ?

**Comment by youness** [comment]
Hi,
It works with:
 composer require owebia/magento2-module-advanced-shipping-setting:2.0.2
Thinks
