### ISSUE TITLE
Shipping method not work as per region 

### ISSUE THREAD

**Issue by nilarocks** [owebia/magento2-module-advanced-shipping-setting#14]
Hello,

I have installed successfully  extension. Also it's working fine as per country id. I want to also change shipping method as per region but here some issue when i change region so that nothing to change in shipping section. But if i select region and refresh page  that shipping method show as per region id. I want to same result when i change region.

See below method i have added in configuration.
For Country Id
`addMethod('id_020', [
    'title'      => "United States Free shipping",
    'enabled'    => in_array($request->dest_country_id, ['US']) && $quote->subtotal > 100.00,	
    'price'      => 0,
]);`

For Region Id
`addMethod('id_030', [
    'title'      => "Alberta Free shipping",
    'enabled'    => in_array($request->dest_region_id, ['66']) && $quote->subtotal > 38.85,	
    'price'      => 0,
]);`

**Comment by nilarocks** [comment]
Any Help?

**Comment by owebia** [comment]
Hi,

Sorry for the delay.  
I will try to fix this today.

Regards,

**Comment by owebia** [comment]
Related to https://github.com/owebia/magento2-module-advanced-shipping-setting/issues/6

**Comment by owebia** [comment]
Fixed with #6  
The new release version is 2.0.6
