### ISSUE TITLE
Uninstall Owebia_AdvancedSettingCore

### ISSUE THREAD

**Issue by marcwales** [owebia/magento2-module-advanced-shipping-setting#16]
Hi, 

I've tried to uninstall both Owebia_AdvancedShippingSetting and Owebia_AdvancedSettingCore via ssh but the second one keeps saying "Owebia_AdvancedSettingCore is not an installed composer package".
This is the code used : php bin/magento module:uninstall Owebia_AdvancedSettingCore

I hope this is solvable because component manager is stuck because of your module and i can't uninstall it via composer... a little loop ;) 

Thanks in advance for your help.

Regards, 
Marc

**Comment by owebia** [comment]
Hi,  
How did you install the module ?  
Regards,

**Comment by marcwales** [comment]
Hi,

I installed following the procedure on github :

php composer.phar require owebia/magento2-module-advanced-shipping-setting:^2.0

Thanks for your help.

Regards.


Le 10 févr. 2017 à 11:57, owebia <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi,
How did you install the module ?
Regards,

**Comment by marcwales** [comment]
Hi Again,

I’ve managed to forced it by using the component manager that worked again after unistalling Owebia_AdvancedShipping.

Hope this was the correct way ;)

Regards,
Marc


Le 10 févr. 2017 à 12:01, Sidney Wagenaar <marcwales@hotmail.fr<mailto:marcwales@hotmail.fr>> a écrit :

Hi,

I installed following the procedure on github :

php composer.phar require owebia/magento2-module-advanced-shipping-setting:^2.0

Thanks for your help.

Regards.


Le 10 févr. 2017 à 11:57, owebia <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi,
How did you install the module ?
Regards,

**Comment by owebia** [comment]
Related to #10
