### ISSUE TITLE
Installation error with composer

### ISSUE THREAD

**Issue by lucav90** [owebia/magento2-module-advanced-shipping-setting#18]
Hi,

when i use composer to install i have this error:

Problem 1
    - owebia/magento2-module-advanced-shipping-setting 2.0.5 requires owebia/magento2-module-advanced-setting-core ^2.0.4 -> satisfiable by owebia/magento2-module-advanced-setting-core[2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - owebia/magento2-module-advanced-shipping-setting 2.0.6 requires owebia/magento2-module-advanced-setting-core ^2.0.4 -> satisfiable by owebia/magento2-module-advanced-setting-core[2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - owebia/magento2-module-advanced-setting-core 2.0.7 requires magento/framework ^100.0|^100.1 -> no matching package found.
    - owebia/magento2-module-advanced-setting-core 2.0.6 requires magento/framework ^100.0 -> no matching package found.
    - owebia/magento2-module-advanced-setting-core 2.0.5 requires magento/framework ^100.0 -> no matching package found.
    - owebia/magento2-module-advanced-setting-core 2.0.4 requires magento/framework ^100.0 -> no matching package found.
    - Installation request for owebia/magento2-module-advanced-shipping-setting ^2.0.5 -> satisfiable by owebia/magento2-module-advanced-shipping-setting[2.0.5, 2.0.6].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by owebia** [comment]
Hi,

Are you executing composer in the magento root directory ?

Regards,

**Comment by owebia** [comment]
Did you create the file auth.json?

http://devdocs.magento.com/guides/v2.0/install-gde/prereq/dev_install.html#create-authjson

**Comment by lucav90** [comment]
hi,
the plugin is correct installed but i don't view the owebia method in shipping methods admin magento page.
i have run the command setup:upgrade, clean cache but nothing is ok.

**Comment by owebia** [comment]
The module will add one carrier: "Advanced Shipping Setting by Owebia".  
Do you see it ?

Do you see Owebia modules in Stores > Configuration > Advanced > Advanced ?

**Comment by lucav90** [comment]
There was enable only the owebia core.

I have enabled the Advanced Shipping Setting and now works!

THANKS
