### ISSUE TITLE
The shipping fees are not changing when I change the country

### ISSUE THREAD

**Issue by pradeepnew** [owebia/magento2-module-advanced-shipping-setting#19]
It shows 404 error in firebug

POST http://35.160.191.194/fr/rest/fr/V1/guest-carts/4e2bde9370e6ab2d92b1db753e05019c/shipping-information 404 (Not Found)

**Comment by owebia** [comment]
Can you give the posted data please ?

Regards,

**Comment by owebia** [comment]
Supposed to be fixed
