### ISSUE TITLE
substr function not reconnized

### ISSUE THREAD

**Issue by youness** [owebia/magento2-module-advanced-shipping-setting#2]
I used this configuration:

addMethod('method_fr', ['title' => 'Livraison île de France', 'enabled' => $request->dest_country_id == 'FR' && in_array(substr($request->dest_postcode, 0, 2), ['75', '78']), 'price' => 10])

And got this error with debug mode :  

Invalid method Owebia\AdvancedShippingSetting\Model\Carrier::substrCallback.

however, 'substr'  is present in allowed functions list.

**Comment by owebia** [comment]
Fixed with commit https://github.com/owebia/magento2-module-advanced-setting-core/commit/870880f20adcd580e706009949232590bbe601bc

**Comment by youness** [comment]
It works now, thinks
