### ISSUE TITLE
Module is installed but no clue how to configure to render in admin and front end

### ISSUE THREAD

**Issue by dangerousal** [owebia/magento2-module-advanced-shipping-setting#24]
Please can you give the exact PATH to the file you need to edit to change admin views to allow inclusion in front end etc....I am not a coder so just this piece of information would be useful

**Comment by owebia** [comment]
Hi,

Did you install the module using composer ?
Have you followed standard steps after a module installation:
php bin/magento cache:clean
php bin/magento setup:upgrade
php bin/magento setup:di:compile
disconnect/reconnect to the backoffice ?

Regards,
A.L.
