### ISSUE TITLE
Error in Owebia\AdvancedSettingCore\Helper\Evaluator

### ISSUE THREAD

**Issue by mdruguet** [owebia/magento2-module-advanced-shipping-setting#26]
Hello,

I have installed via composer the addon and i'm trying to configure it, but nothing appears in front-office. When i click on the bug in order to debug my config, i see this : 

Carrier[owsh1].getConfig - Error - Recoverable Error: Argument 1 passed to Owebia\AdvancedSettingCore\Helper\Evaluator::setCallbackManager() must be an instance of Owebia\AdvancedSettingCore\Model\CallbackHandler, instance of Owebia\AdvancedShippingSetting\Model\Carrier given, called in C:\xampp4\htdocs\cath\dag\magento2\vendor\owebia\magento2-module-advanced-setting-core\Helper\Config.php on line 84 and defined in C:\xampp4\htdocs\cath\dag\magento2\vendor\owebia\magento2-module-advanced-setting-core\Helper\Evaluator.php on line 304 

Could you help me please?

Best regards

**Comment by owebia** [comment]
Hi,

You are using the version 2.0.4 of AdvancedShippingSetting instead of the last version 2.0.7.
Please update the version installed with composer.

Regards,

**Comment by mdruguet** [comment]
Great, thanks a lot

Best regards
