### ISSUE TITLE
Using the special function {count …}

### ISSUE THREAD

**Issue by NailsPlus** [owebia/magento2-module-advanced-shipping-setting#27]
Hi, I am trying to configure the Advanced Shipping to add $5 Oversize fee to all products at the checkout that have color Yellow as their attribute. 

Please note that I am not a skilled developer. The last time I did development was 10 years ago :)

To do this, using your examples I like to add this code to the extension:

{
   "id_027": {
      "label": "If at least one product has the attribute 'color' equal to 'Yellow'",
      "conditions": "{count items where product.attribute.color=='Yellow'} > 0",
      "fees": 5
   },
   "id_028": {
      "label": "If all items have the option 'size' greater or equal to '1'",
      "conditions": "{count items where item.option.size>='1'} == {cart.qty}",
      "fees": 5
   }
} 

Could you please show me how to do this? 

I really appreciate your help.

**Comment by owebia** [comment]
Do you want to add a $5 fee for every yellow product?

If yes, try this:
```
{
    "id_027": {
        "label": "Oversize fee",
        "fees": "5 * {count items where product.attribute.color=='Yellow'}"
    }
}
```

Regards,
A.L.

**Comment by owebia** [comment]
PS: you are not posting an issue to the right project. And please, do not use issues to ask for configuration support.

Regards,
A.L.
