### ISSUE TITLE
2.2  Compatibility

### ISSUE THREAD

**Issue by gewaechshaus** [owebia/magento2-module-advanced-shipping-setting#28]
Hey,

are there plans when the MCE 2.2 compatibility will be realized?

Many thanks
Jan

**Comment by owebia** [comment]
Hi,

There is no planning yet. Did you try to install? Do you have an error?
It will come but when I will have time for testing that.

Regards,
A.L.

**Comment by gewaechshaus** [comment]
Hi A.L.

yes, it's running so far... I did manualy push it into app/code. If I remember right, there was only a small issue with compilation.

Greetings
Jan

**Comment by kartguru** [comment]
I'm kinda offline atm so from memory my issues were related to magento/framework. On closer inspection it looks to be a owebia/magento2-module-advanced-setting-core issue

cheers
- michael

**Comment by ofourny** [comment]
Indeed the composer.json in owebia/magento2-module-advanced-setting-core need to be updated for Magento 2.2.

Regards,

OF

**Comment by owebia** [comment]
Thanks, I will have a look.

Regards,
A.L.

**Comment by gewaechshaus** [comment]
It looks like the shipping methods configuration in the backend is broken 2.

Greetings
Jan

**Comment by gtlt** [comment]
Hello,
I made PR on :
- magento2-module-advanced-setting-core [#3](https://github.com/owebia/magento2-module-advanced-setting-core/pull/3) (+need a new tag 2.2.x)
- magento2-module-advanced-shipping-setting https://github.com/owebia/magento2-module-advanced-shipping-setting/pull/29

There are more than magento/framework to upgrade to be magento 2.2 CE compliant. php-7.1 needs also to be added in composer.
@gewaechshaus could you test with my PRs to check if backend config is broken ? On my side it looks ok (magento 2.2.0 + php 7.1.10).

**Comment by gewaechshaus** [comment]
@gtlt - many thanks - as far as I can see you only updated both related composer.json?

**Comment by owebia** [comment]
Thanks @gtlt for the PR's.
Both have been included with some fixes in last version of the extension : 2.0.8

**Comment by gewaechshaus** [comment]
@owebia - we still got the issue with broken backend shipping methods... As it is a live system, I can only debug it sensitive. Here's what I got:

1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 /var/www/html/vendor/magento/module-config/Model/Config/Backend/Serialized.php(55): Magento\Framework\Serialize\Serializer\Json->unserialize('a:2:{s:18:"_149...')
#1 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(601): Magento\Config\Model\Config\Backend\Serialized->_afterLoad()
#2 /var/www/html/generated/code/Magento/Config/Model/Config/Backend/Serialized/ArraySerialized/Interceptor.php(323): Magento\Framework\Model\AbstractModel->afterLoad()
#3 /var/www/html/vendor/magento/module-config/Block/System/Config/Form.php(438): Magento\Config\Model\Config\Backend\Serialized\ArraySerialized\Interceptor->afterLoad()
#4 /var/www/html/vendor/magento/module-config/Block/System/Config/Form.php(348): Magento\Config\Block\System\Config\Form->getFieldData(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), 'carriers/custom...')
#5 /var/www/html/vendor/magento/module-config/Block/System/Config/Form.php(324): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'carriers/custom...', '', '')
#6 /var/www/html/vendor/magento/module-config/Block/System/Config/Form.php(264): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
#7 /var/www/html/vendor/magento/module-config/Block/System/Config/Form.php(210): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#8 /var/www/html/vendor/magento/module-config/Block/System/Config/Form.php(549): Magento\Config\Block\System\Config\Form->initForm()
#9 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#10 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#12 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#13 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#14 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#15 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#16 /var/www/html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#17 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#18 /var/www/html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/var/www/html/v...', Array)
#19 /var/www/html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#20 /var/www/html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#21 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#22 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#24 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#25 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#26 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#27 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#28 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#29 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#30 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#31 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#32 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#33 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#34 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#35 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#36 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#37 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#38 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#39 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#40 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#41 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#42 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#43 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#44 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#45 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#46 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#47 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#48 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#49 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#50 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#51 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#52 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#53 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#54 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#55 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#56 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#57 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#58 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#59 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#60 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#61 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#62 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#63 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#64 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#65 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#66 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#67 /var/www/html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#68 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#69 /var/www/html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#70 /var/www/html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /var/www/html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /var/www/html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#74 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#75 /var/www/html/vendor/msp/shield/Plugin/AppInterfacePlugin.php(113): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#76 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): MSP\Shield\Plugin\AppInterfacePlugin->aroundLaunch(Object(Magento\Framework\App\Http\Interceptor), Object(Closure))
#77 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#78 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, NULL)
#79 /var/www/html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#80 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

**Comment by owebia** [comment]
Hi,

Not sure it was related to this module.  
Are you using other shipping modules?

Regards,  
A.L.

**Comment by gewaechshaus** [comment]
Hi @owebia,
actualy trying to trace it down... 

Stumbled upon:
https://magento.stackexchange.com/questions/194010/magento-2-2-unable-to-unserialize-value/196825

Did try the recommended solutions without success.

**Comment by gewaechshaus** [comment]
@owebia - it looks like this related to M2.2.0 as we can't see your module directly calling unserialize...

**Comment by gewaechshaus** [comment]
This issue is related to MagePal_CustomShippingRate module...

**Comment by owebia** [comment]
@gewaechshaus Thanks for the clarification.

**Comment by gewaechshaus** [comment]
@owebia - no problem! thanks for providing your code!!!
