### ISSUE TITLE
[Feature Request] Add translation mechanism

### ISSUE THREAD

**Issue by gtlt** [owebia/magento2-module-advanced-shipping-setting#37]
I made a PR #36 to allow easier maintainability for translations.
In case of multiple storeview, we don't need to define a shipping setting for each of them.
Translations can then be managed from you translation module/csv

**Comment by owebia** [comment]
Hi, thanks for your contribution.

In most case, the shipping configuration is done by someone who has no access to magento files.
So I'm not sure it correspond to user's needs.

I will let this issue opened and see if other users are interrested.
(Translation mecanism can have side effects like unwanted translation of strings).

Best Regards,
A.L.

**Comment by gtlt** [comment]
Ok, thank you I didn't realized that. I will go with an override/plugin for my usecase.

What do you think about adding a translate function ? something like :
"id": {
      "label": "translate('translated label')"
}

**Comment by owebia** [comment]
Available in 2.4.* version
