### ISSUE TITLE
Question tracking url

### ISSUE THREAD

**Issue by little-english** [owebia/magento2-module-advanced-shipping-setting#41]
Good morning, 
In Magento 1, we have the option to add the option: "tracking_url" in the configuration. I did not find in the documentation of magento 2. Do we also have this possibility ?

**Comment by owebia** [comment]
Hi,
No, there isn't this option in M2 module.
Best Regards,
A.L.

**Comment by little-english** [comment]
Bonjour, 
Merci pour votre retour. 
Avons-nous une solution (dans les modules payants) de pouvoir utiliser cette option ?

**Comment by owebia** [comment]
Non, pas actuellement.
J'ai eu peu de demandes pour cette fonctionnalité mais si elle venait à être réclamée, peut-être qu'elle serait implémentée.
A.L.

**Comment by gabrieljadeau** [comment]
Hi @owebia,

Could you please let me know if I can set the "tracking_url" when defining the carrier, like this : 

addMethod('dhl_0001', [
    'title' => "DHL Express delivery",
    'enabled' => in_array($request->dest_country_id, ['FR']),
    'price' => !($request->free_shipping) * array_reduce([['*', 11]], function ($carry, $item) use ($request) {
            if (isset($carry)) return $carry;
            if (isset($item[0]) && ($request->package_weight <= $item[0] || $item[0] == '*')) {
                $carry = $item[1];
            }
            return $carry;
        }),
     'tracking_url' => "https://www.carrier-website.com/?trackingNumber={{trackingNumber}}"
]);


I beleive that's not possible and I will have to add it as in the module, it seems that you are defining it as a store configuration attribute, not in the addMethod? 

Thanks for your answer, much appreciated.

Best,

G.

**Comment by owebia** [comment]
Yes, it is only available as a global carrier value, you can define it in the addMethod.

Best Regards,
A.L.
