### ISSUE TITLE
Montant des frais de port dans back office

### ISSUE THREAD

**Issue by little-english** [owebia/magento2-module-advanced-shipping-setting#42]
Bonjour, 

Je passe une commande via le back office. Cette commande a un montant supérieur à 60euros. D'après mes règles Owebia mes frais de port son gratuit. Je n'ai aucun problème mes frais de port son gratuit. Cependant, si je souhaite renouveler cette commande, toujours via le backoffice, je me retrouve avec des frais de port alors que le montant de cette commande est aussi supérieur à 60euros. 

Voici ma configuration Owebia: 

`//BE, LU DPD
addMethod('dpd', [
    'title' => "DPD",
    'price'      => !$request->free_shipping * array_reduce([ [60, 0], ['*', 5] ], function ($carry, $item) {
		        global $quote;
		        if (isset($carry)) return $carry;
		        if (isset($item[0]) && ($quote->grand_total >= $item[0] || $item[0] == '*')) {
		            $carry = $item[1];
		        }
		        return $carry;
		    }),
    'enabled' => in_array($request->dest_country_id, ['BE','LU']),
                        	
]);

`

![capture957](https://user-images.githubusercontent.com/7421398/46403753-ab71ee80-c703-11e8-89b2-1efcc777e2f4.PNG)
![capture97](https://user-images.githubusercontent.com/7421398/46403754-ac0a8500-c703-11e8-9438-46ad128a3789.PNG)

**Comment by owebia** [comment]
Bonjour,

Il vaut mieux ne pas utiliser la variable `$quote->grand_total` car elle contient les frais de livraison. Le comportement est donc parfois imprévisible en fonction du moment où Magento demande les frais de livraison.  
Il vaut mieux utiliser `$request->package_value` ou `$request->package_value_with_discount`.

Cordialement,  
A.L.
