### ISSUE TITLE
Error Unsupported expression PhpParser\Node\Stmt\Expression

### ISSUE THREAD

**Issue by bhargav-rupapara** [owebia/magento2-module-advanced-shipping-setting#43]
![screenshot from 2018-10-03 22-19-08](https://user-images.githubusercontent.com/43367702/46425840-69c06280-c75a-11e8-9ce1-62355ca38e31.png)
I'm facing this error on checkout page, 

below is the config I've added : 

addMethod('method1', [
    'title' => "Standard Shipping",
    'price' => 10
]);

magento version is 2.2.3

php-parser composer.json

{
    "name": "nikic/php-parser",
    "description": "A PHP parser written in PHP",
    "keywords": ["php", "parser"],
    "type": "library",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Nikita Popov"
        }
    ],
    "require": {
        "php": ">=5.4",
        "ext-tokenizer": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0"
    },
    "autoload": {
        "psr-4": {
            "PhpParser\\": "lib/PhpParser"
        }
    },
    "bin": ["bin/php-parse"],
    "extra": {
        "branch-alias": {
            "dev-master": "2.0-dev"
        }
    }
}

advance shipping composer.json

{
    "name": "owebia/magento2-module-advanced-shipping-setting",
    "description": "N/A",
    "require": {
        "php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0",
        "magento/magento-composer-installer": "^0.1.11",
        "owebia/magento2-module-advanced-setting-core": "^2.1.0"
    },
    "type": "magento2-module",
    "license": [
        "proprietary"
    ],
    "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "Owebia\\AdvancedShippingSetting\\": ""
        }
    }
}

advance setting core module composer.json

{
    "name": "owebia/magento2-module-advanced-setting-core",
    "description": "N/A",
    "require": {
        "php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0",
        "magento/framework": "^100.0|^101.0",
        "magento/module-backend": "^100.0",
        "magento/module-catalog": "^100.0|^101.0|^102.0",
        "magento/module-catalog-inventory": "^100.0",
        "magento/module-checkout": "^100.0",
        "magento/module-config": "^100.0|^101.0",
        "magento/module-customer": "^100.0|^101.0",
        "magento/module-eav": "^100.0|^101.0",
        "magento/module-quote": "^100.0|^101.0",
        "magento/module-store": "^100.0",
        "magento/module-variable": "^100.0",
        "magento/magento-composer-installer": "^0.1.11",
        "nikic/php-parser": "2.0.*"
    },
    "type": "magento2-module",
    "license": [
        "proprietary"
    ],
    "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "Owebia\\AdvancedSettingCore\\": ""
        }
    }
}

**Comment by bhargav-rupapara** [comment]
I also tried to look into the class : Owebia\AdvancedSettingCore\Helper\Evaluator line 564 from where error is throwing. 

I think issue is I couldn't find class PhpParser\Node\Stmt\Expression in nikic/php-parser module.

**Comment by owebia** [comment]
Hi,

This error is thrown because you are using the version 4 of nikic/php-parser.
(related to: https://github.com/owebia/magento2-module-advanced-setting-core/issues/6)

This should work with the last release of the extension.

Best Regards,
A.L.
