### ISSUE TITLE
How I set Carrier Title for different method

### ISSUE THREAD

**Issue by pravinagham** [owebia/magento2-module-advanced-shipping-setting#44]
@owebia  - Question - I can see there are only title, description and price we can set in addMethod. But How can I set Carrier Title for different method.

At checkout page, we have Select Method | Method Title | Carrier Title.
Want to set Carrier Title

**Comment by owebia** [comment]
Hi,

The Carrier Title is a global value that can be changed in the configuration as shown bellow:  
![magento2-module-advanced-shipping-setting-1](https://user-images.githubusercontent.com/604741/47951889-79081b00-df67-11e8-9700-5aa943255795.png)

If you need to have multiple carriers, you have to get [Unlimited Carriers add-on for Advanced Shipping](https://fr.store.owebia.com/magento2-module-adv-ship-unlimited-carriers-addon.html).

Best Regards,  
A.L.
