### ISSUE TITLE
Method description is not shown

### ISSUE THREAD

**Issue by celocore** [owebia/magento2-module-advanced-shipping-setting#48]
If a description is specified in the method declaration, it is not visible in the frontend.
Example:
<pre>
addMethod('default', [
    'title'       => "Fixe Versandkosten",
    'price'       => 8.20,
    'description' => "Standardversand",
    'enabled'     => count(
                         array_filter($request->all_items, function ($item) {
                             return $item->product->bulky_item;
                         })
                     ) < 1,
    ]);
</pre>

**Comment by owebia** [comment]
Hi,

The description data is not available in Magento front.

Best Regards,
A.L.
