### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by Userr017** [owebia/magento2-module-advanced-shipping-setting#49]
This extension doesn't not compatible with php 7.2?

**Comment by Userr017** [comment]
I have another your extension but it include also this extension. 

This is issue when enabled php 7.2.
![issue](https://user-images.githubusercontent.com/26794034/50378758-08fe4300-0642-11e9-9b6e-f382d1c5f6e2.JPG)

**Comment by owebia** [comment]
Hi,

You should be able to download last versions of paid modules from your customer account on Owebia Store.  
Tell me if you encounter any issue.

Best Regards,
A.L.

**Comment by Userr017** [comment]
It works, thanks!
