### ISSUE TITLE
Unsupported expression Magento\Quote\Model\Quote\Item

### ISSUE THREAD

**Issue by rzwinge** [owebia/magento2-module-advanced-shipping-setting#5]
Hello,
i try to build a method to decide between 3 methods.

`
addMethod('id_002', [
    'title'   => 	array_reduce(["DHL-Versand", "Versandkostenfrei"], function($result, $shipping) {
        global $quote;
        if ($shipping == "Versandkostenfrei" && $quote->grand_total >= 350.00) {
            $result = $shipping;
        }

        global $request;
        if ($shipping == "DHL-Versand") {

            $extras = array_filter($request->all_items, function($item) {
                return count(array_intersect($item->product->category_ids, [6270, 6271, 6328, 6365])) >= 1 ? true : false;
            });
        }

        return $result;
    }, "Spedition"),
    'price'   => 	0.00
]);
`

But i get following error: Unsupported expression Magento\Quote\Model\Quote\Item

If i remove this block
`$extras = array_filter($request->all_items, function($item) {
                return count(array_intersect($item->product->category_ids, [6270, 6271, 6328, 6365])) >= 1 ? true : false;
            });`
everything is ok.
It is a bug or did i have forgotten something?

Debugging: In variable $extras is an array of size 1 and it is alright. But after that the error appears.

**Comment by owebia** [comment]
Hi,
Please, can you send me your whole configuration (the one posted on github is not correctly formatted) and the debug file (in var/log) by email ?

Are you using the last version of the extension ?

Thank you

**Comment by rzwinge** [comment]
Hi,
i could not find your mail.

Are attachments ok?
[owebia_advancedsettingcore.txt](https://github.com/owebia/magento2-module-advanced-shipping-setting/files/476955/owebia_advancedsettingcore.txt)
[methods.txt](https://github.com/owebia/magento2-module-advanced-shipping-setting/files/476956/methods.txt)

Yes, i use 2.0.4.

**Comment by owebia** [comment]
Can you try to update owebia/magento2-module-advanced-setting-core and tell me if this is fixed ?

**Comment by rzwinge** [comment]
Yes! :)

**Comment by owebia** [comment]
Thank you for your feedback

**Comment by rzwinge** [comment]
Thank you for your help :)
