### ISSUE TITLE
Online documentation is down

### ISSUE THREAD

**Issue by rseon** [owebia/magento2-module-advanced-shipping-setting#50]
Since today I can't read documentation located at http://htmlpreview.github.io/?https://github.com/owebia/magento2-module-advanced-shipping-setting/blob/master/view/doc_en_US.html because of ERR_NAME_NOT_RESOLVED on query.yahooapis.com

**Comment by owebia** [comment]
Hi, this is related to this issue:  
https://github.com/htmlpreview/htmlpreview.github.com/issues/66

**Comment by rseon** [comment]
Ok thank you !
I've seen this solution in a comment : https://raw.githack.com/ (https://github.com/htmlpreview/htmlpreview.github.com/issues/65#issuecomment-451517562)

**Comment by owebia** [comment]
Fixed in commit 63ba5e9e40fa11f13c3ee1bbe4299947c2e00a43
