### ISSUE TITLE
Shipping table rates

### ISSUE THREAD

**Issue by cxperts** [owebia/magento2-module-advanced-shipping-setting#52]

**Comment by cxperts** [comment]
Hi,

I have issue about my shipping method . we have create table rate .cvs file and import our magento 2 templates but as soon we go to the checkout Process areas the shipping price not calculate the price which we have mention in the file with products size its show as error. ( This shipping method is not available. To use this shipping method, please contact us. ) its any body help me to solve this problem.

**Comment by owebia** [comment]
Hi,

This is not the good place to ask help on Magento 2 table rate files.

Best Regards,
A.L.
