### ISSUE TITLE
Shipping estimate not work

### ISSUE THREAD

**Issue by sdasun** [owebia/magento2-module-advanced-shipping-setting#6]
**How to recreate**
Disable all other shipping methods.
Add some item to cart and visit checkout page.
You will not get the shipping estimate as expected (have to refresh the whole page)

**Comment by owebia** [comment]
Can you give more details, please ?

- the version of the module
- the version of Magento
- the configuration of the module
- the items in cart
- the result expected
- the result obtained
- screenshots if needed

Thanks

**Comment by natahanielmeyer** [comment]
I had the same issue won't reload the shipping if all of the other ones are disabled. For example, if zip code needs to be 2003 and it isn't shipping won't show up but when I change the code to 2003 it doesn't reload the options only does it if one of the other shipping types is enabled.

**Comment by sdasun** [comment]
Sorry, That. I'm not able to reproduce since the project is in production mode. I guess it can reproduce by disabling every other shipping method on any version. I've been using 2.1.

**Comment by arlycreative** [comment]
I've got the same problem and @owebia told me to add some ajax validation in order for this to work without any other shipping methods enabled. I'm not sure how to do this either. Maybe you could provide a fix/patch for this common problem?

I know you provided a link to a fix for this for your old module but can't figure out how to apply that to this new one @owebia

**Comment by tlygnersjo** [comment]
I've got the same problem and @owebia told me to add some ajax validation in order for this to work without any other shipping methods enabled. I'm not sure how to do this either. Maybe you could provide a fix/patch for this common problem?

I know you provided a link to a fix for this for your old module but can't figure out how to apply that to this new one @owebia

**Comment by owebia** [comment]
Sorry for the delivery time of this fix

![configuration settings stores magento admin](https://cloud.githubusercontent.com/assets/604741/22971025/8f5c303e-f374-11e6-9a1b-480fe6fe84fc.png)

Required fields must be selected in the module configuration

**Comment by owebia** [comment]
Thanks to @bchatard for the fix given a long time ago

**Comment by owebia** [comment]
The new release version is 2.0.6
