### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by guillaumebabik** [owebia/magento2-module-advanced-shipping-setting#8]
Hi,

When using  ./magento setup:di:compile, it returns an error : 
PHP Fatal error:  Class 'Owebia\AdvancedSettingCore\Block\System\Config\Form\Field\AbstractField' not found in /var/www/html/app/code/Owebia/AdvancedShippingSetting/Block/System/Config/Form/Field/About.php on line 9

I am using version 2.0.5 on Magento Enterprise Edition 2.1.0

Many thanks,

Regards

**Comment by owebia** [comment]
Hi,

How did you install the extension ? Via composer ?

**Comment by guillaumebabik** [comment]
Hi,

No, I uncompress the archive on my Magento directory.
=> I can't use Composer on my server

But the Magento Enterprise Edition core files are under /vendor directory and not /app/code

Many thanks,

Regards,

**Comment by owebia** [comment]
The extension can only be installed with composer because it has somes dependencies.

Regards,

**Comment by guillaumebabik** [comment]
Could you provide the dependencies in order to get manually ?

Regards

**Comment by owebia** [comment]
They are indicated in composer.json :  
https://github.com/owebia/magento2-module-advanced-shipping-setting/blob/master/composer.json
https://github.com/owebia/magento2-module-advanced-setting-core/blob/master/composer.json
https://github.com/nikic/php-parser/blob/master/composer.json
