### ISSUE TITLE
Give blank page after install module

### ISSUE THREAD

**Issue by nilarocks** [owebia/magento2-module-advanced-shipping-setting#9]
Hello,

I have installed this module using command "composer require owebia/magento2-module-advanced-shipping-setting:^2.0". After Successfully install, i have run "php bin/magento setup:upgrade" command  also "php bin/magento setup:static-content:deploy" but when i check in backend it's give blank page. Other shipping method not show.

I am using magento version  2.0.7.

Thanks

**Comment by owebia** [comment]
Hi,
Have you tried to clear the cache ? And to logout/login from backend ?
Regards,
A.L.

**Comment by nilarocks** [comment]
Hello owebia

Thanks For reply

Yes i have clear cache and  logout from backend and agian login but still issue not resolved

Also I have checked var/log/system.txt file  in this file give a below error

`main.CRITICAL: Invalid method Owebia\AdvancedShippingSetting\Block\System\Config\Form\Field\Config::translate(Array
(
    [0] => Advanced Shipping Setting Configuration
)
)`

**Comment by owebia** [comment]
It seems that you are using an old version of the extension.

This bug has been fixed in version 2.0.2.

Regards,  
A.L.

**Comment by owebia** [comment]
Original issue : https://github.com/owebia/magento2-module-advanced-shipping-setting/issues/1
